#!/usr/bin/env bash

python -m distant_supervision.train_bert --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run000 --num_train_epoch 10  --ignore_no_mentions --fp16 --learning_rate 3e-5
#python -m distant_supervision.train_bert --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run001 --num_train_epoch 10  --ignore_no_mentions --fp16 --learning_rate 3e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev.json distant_supervision/data/BioNLP-ST_2013/test.json --direct_weight 0.2
python -m distant_supervision.train_bert --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run002 --num_train_epoch 10  --ignore_no_mentions --fp16 --learning_rate 3e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev.json distant_supervision/data/BioNLP-ST_2013/test.json --direct_weight 0.5
python -m distant_supervision.train_bert --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run003 --num_train_epoch 10  --ignore_no_mentions --fp16 --learning_rate 3e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev.json distant_supervision/data/BioNLP-ST_2013/test.json --direct_weight 1.0
python -m distant_supervision.train_bert --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run004 --num_train_epoch 10  --ignore_no_mentions --fp16 --learning_rate 3e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev.json distant_supervision/data/BioNLP-ST_2013/test.json --direct_weight 2.0
python -m distant_supervision.train_bert --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run005 --num_train_epoch 10  --ignore_no_mentions --fp16 --learning_rate 3e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev.json distant_supervision/data/BioNLP-ST_2013/test.json --direct_weight 10.0
python -m distant_supervision.train_bert --bert ~/data/scibert_scivocab_uncased --train distant_supervision/data/BioNLP-ST_2013/train.hdf5 --dev distant_supervision/data/BioNLP-ST_2013/dev.hdf5 --gradient_accumulation_steps 16 --output_dir distant_supervision/runs/run006 --num_train_epoch 10  --ignore_no_mentions --fp16 --learning_rate 3e-5 --direct_data distant_supervision/data/BioNLP-ST_2011/all.hdf5 --pair_blacklist distant_supervision/data/BioNLP-ST_2013/dev.json distant_supervision/data/BioNLP-ST_2013/test.json --direct_weight 50.0
