GENE_OR_GENE_PRODUCT = 'Gene_or_gene_product'
CHEMICAL = 'Simple_chemical'
COMPLEX = 'Complex'
ENTITY = 'Entity'
LOCATION = 'Cellular_component'
TRANSPORT = 'Transport'
ACTIVATION = 'Activation'
INACTIVATION = 'Inactivation'
SUMOYLATION = 'Sumoylation'
DESUMOYLATION = 'Desumoylation'
PHOSPHORYLATION = 'Phosphorylation'
DEPHOSPHORYLATION = 'Dephosphorylation'
UBIQUITINYLATION = 'Ubiquitinylation'
DEUBIQUITINYLATION = 'Deubiquitinylation'
ACETYLATION = 'Acetylation'
DEACETYLATION = 'Deacetylation'
METHYLATION = 'Methylation'
DEMETHYLATION = 'Demethylation'
POSITIVE_REGULATION = 'Positive_regulation'
NEGATIVE_REGULATION = 'Negative_regulation'
REGULATION = 'Regulation'
DEGRADATION = 'Degradation'
BINDING = 'Binding'
DISSOCIATION = 'Dissociation'

SIMPLE_EVENTS = [ACETYLATION, ACTIVATION, DEACETYLATION, DEGRADATION, DEMETHYLATION, DEPHOSPHORYLATION, DEUBIQUITINYLATION,
                 INACTIVATION, METHYLATION, PHOSPHORYLATION, UBIQUITINYLATION]
