#!/usr/bin/env bash
#
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_01 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  6006, "pytorch_seed": 6006, "numpy_seed": 6006}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_02 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  7007, "pytorch_seed": 7007, "numpy_seed": 7007}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_03 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  8008, "pytorch_seed": 8008, "numpy_seed": 8008}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_04 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  9009, "pytorch_seed": 9009, "numpy_seed": 9009}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_05 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  1001, "pytorch_seed": 1001, "numpy_seed": 8008}'
#allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_06 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  2002, "pytorch_seed": 6006, "numpy_seed": 6006}'
#allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_07 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  3003, "pytorch_seed": 7007, "numpy_seed": 7007}'
#allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_08 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  4004, "pytorch_seed": 8008, "numpy_seed": 8008}'
#allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_09 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  5005, "pytorch_seed": 9009, "numpy_seed": 9009}'
#allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_10 -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  1000, "pytorch_seed": 1001, "numpy_seed": 8008}'
#
#
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_01 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  6006, "pytorch_seed": 6006, "numpy_seed": 6006}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_02 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  7007, "pytorch_seed": 7007, "numpy_seed": 7007}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_03 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  8008, "pytorch_seed": 8008, "numpy_seed": 8008}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_04 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  9009, "pytorch_seed": 9009, "numpy_seed": 9009}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_05 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  1001, "pytorch_seed": 1001, "numpy_seed": 8008}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_06 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  2002, "pytorch_seed": 6006, "numpy_seed": 6006}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_07 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  3003, "pytorch_seed": 7007, "numpy_seed": 7007}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_08 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  4004, "pytorch_seed": 8008, "numpy_seed": 8008}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_09 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  5005, "pytorch_seed": 9009, "numpy_seed": 9009}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_10 -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  1000, "pytorch_seed": 1001, "numpy_seed": 8008}'


allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_01_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  6006, "pytorch_seed": 6006, "numpy_seed": 6006,
  "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_02_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  7007, "pytorch_seed": 7007, "numpy_seed": 7007, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_03_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  8008, "pytorch_seed": 8008, "numpy_seed": 8008, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_04_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  9009, "pytorch_seed": 9009, "numpy_seed": 9009, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_05_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  1001, "pytorch_seed": 1001, "numpy_seed": 8008, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_06_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  2002, "pytorch_seed": 6006, "numpy_seed": 6006, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_07_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  3003, "pytorch_seed": 7007, "numpy_seed": 7007, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_08_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  4004, "pytorch_seed": 8008, "numpy_seed": 8008, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_09_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  5005, "pytorch_seed": 9009, "numpy_seed": 9009, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp11_10_no_direct -o '{"train_data_path": "data/BioNLP-ST_2011/train_masked.json", "validation_data_path": "data/BioNLP-ST_2011/dev_masked.json", "random_seed":  1000, "pytorch_seed": 1001, "numpy_seed": 8008, "model": {"sent_loss_weight": 0}}'


allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_01_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  6006, "pytorch_seed": 6006, "numpy_seed": 6006, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_02_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  7007, "pytorch_seed": 7007, "numpy_seed": 7007, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_03_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  8008, "pytorch_seed": 8008, "numpy_seed": 8008, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_04_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  9009, "pytorch_seed": 9009, "numpy_seed": 9009, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_05_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  1001, "pytorch_seed": 1001, "numpy_seed": 8008, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_06_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  2002, "pytorch_seed": 6006, "numpy_seed": 6006, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_07_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  3003, "pytorch_seed": 7007, "numpy_seed": 7007, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_08_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  4004, "pytorch_seed": 8008, "numpy_seed": 8008, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_09_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  5005, "pytorch_seed": 9009, "numpy_seed": 9009, "model": {"sent_loss_weight": 0}}'
allennlp train allennlp_config/config.json --include-package relex -s runs/bionlp13_10_no_direct -o '{"train_data_path": "data/BioNLP-ST_2013/train_masked.json", "validation_data_path": "data/BioNLP-ST_2013/dev_masked.json", "random_seed":  1000, "pytorch_seed": 1001, "numpy_seed": 8008, "model": {"sent_loss_weight": 0}}'



